public-resources:
  leantime:
    name: "Leantime"
    mode: http
    full-domain: leantime.labmatt.com
    targets:
      - site: faithful-brachyurophis-fasciolatus
        method: http
        hostname: ingress-nginx-controller.ingress-nginx.svc.cluster.local
        port: 80
    auth:
      sso-enabled: false
    rules:
      - action: allow
        match: country
        value: US
        priority: 1
