public-resources:
  wekan:
    name: "Wekan"
    mode: http
    full-domain: wekan.labmatt.com
    targets:
      - site: faithful-brachyurophis-fasciolatus
        method: http
        hostname: ingress-nginx-controller.ingress-nginx.svc.cluster.local
        port: 80
    rules:
      - action: allow
        match: country
        value: US
        priority: 1
