apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cross-seed-config
  namespace: downloads-standard
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-provisioner
  resources:
    requests:
      storage: 2Gi
