apiVersion: v1
kind: Secret
metadata:
  name: postgres-sonarr-anime-reflection
  namespace: downloads-standard
  annotations:
    reflector.v1.k8s.emberstack.com/reflects: "database/postgres-sonarr-anime"
data: {}
