apiVersion: v1
kind: Secret
metadata:
  name: postgres-radarr-portuguese-reflection
  namespace: downloads-standard
  annotations:
    reflector.v1.k8s.emberstack.com/reflects: "database/postgres-radarr-portuguese"
data: {}
