{
 "title": "Promox",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Host RAM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (host) (node_memory_MemTotal_bytes{job=\"node-exporter\", role=\"host\"} \n- node_memory_MemAvailable_bytes{job=\"node-exporter\", role=\"host\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Host CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (host) (rate(node_cpu_seconds_total{job=\"node-exporter\", role=\"host\", mode!=\"idle\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nicholas RAM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=\"node-exporter\", host=\"nicholas\", role!=\"host\"} \n- node_memory_MemAvailable_bytes{job=\"node-exporter\", host=\"nicholas\", role!=\"host\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Nicholas CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by (hostname) (rate(node_cpu_seconds_total{job=\"node-exporter\", host=\"nicholas\", role!=\"host\", mode!=\"idle\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Livio RAM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=\"node-exporter\", host=\"livio\", role!=\"host\"} \n- node_memory_MemAvailable_bytes{job=\"node-exporter\", host=\"livio\", role!=\"host\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Livio CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum by (hostname) (rate(node_cpu_seconds_total{job=\"node-exporter\", host=\"livio\", role!=\"host\", mode!=\"idle\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Razlo RAM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=\"node-exporter\", host=\"razlo\", role!=\"host\"} \n- node_memory_MemAvailable_bytes{job=\"node-exporter\", host=\"razlo\", role!=\"host\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Razlo CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "sum by (hostname) (rate(node_cpu_seconds_total{job=\"node-exporter\", host=\"razlo\", role!=\"host\", mode!=\"idle\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}