{
 "title": "TrueNAS",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "(scale_truenas_truenas_cpu_usage_cpu_cpu0 + scale_truenas_truenas_cpu_usage_cpu_cpu1 + scale_truenas_truenas_cpu_usage_cpu_cpu2 + scale_truenas_truenas_cpu_usage_cpu_cpu3 + scale_truenas_truenas_cpu_usage_cpu_cpu4 + scale_truenas_truenas_cpu_usage_cpu_cpu5 + scale_truenas_truenas_cpu_usage_cpu_cpu6 + scale_truenas_truenas_cpu_usage_cpu_cpu7) / 100",
     "legendFormat": "TrueNAS"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "(scale_truenas_truenas_meminfo_total_total - scale_truenas_truenas_meminfo_available_available) / 1024 / 1024 / 1024",
     "legendFormat": "TrueNas"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum({__name__=~\"scale_truenas_truenas_disk_stats__.*_reads\"})",
     "legendFormat": "Reads"
    },
    {
     "expr": "sum({__name__=~\"scale_truenas_truenas_disk_stats__.*_writes\"})",
     "legendFormat": "Writes"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "scale_truenas_zpool_used", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "sleipnir/k8s Snapshot Overhead",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "scale_truenas_dataset_k8s_used", "legendFormat": "sleipnir/k8s used" },
    {
     "expr": "scale_truenas_dataset_k8s_snapshot_used",
     "legendFormat": "snapshot overhead"
    }
   ]
  },
  {
   "title": "sleipnir/k8s-iscsi Snapshot Overhead",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "scale_truenas_dataset_k8s_iscsi_used",
     "legendFormat": "sleipnir/k8s-iscsi used"
    },
    {
     "expr": "scale_truenas_dataset_k8s_iscsi_snapshot_used",
     "legendFormat": "snapshot overhead"
    }
   ]
  }
 ]
}