apiVersion: v1
kind: Secret
metadata:
  name: leantime-postgres-credentials
  namespace: project-management
  annotations:
    reflector.v1.k8s.emberstack.com/reflects: "code-for-boston/leantime-postgres-credentials"
