apiVersion: apps/v1
kind: Deployment
metadata:
  name: newt
  namespace: tunnel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: newt
  template:
    metadata:
      labels:
        app: newt
    spec:
      containers:
      - name: newt
        image: fosrl/newt:1.15.0
        env:
        - name: PANGOLIN_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: newt-auth
              key: endpoint
        - name: NEWT_ID
          valueFrom:
            secretKeyRef:
              name: newt-auth
              key: id
        - name: NEWT_SECRET
          valueFrom:
            secretKeyRef:
              name: newt-auth
              key: secret
