deploymentMode: SingleBinary

loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  schemaConfig:
    configs:
      - from: "2026-01-01"
        store: tsdb
        object_store: filesystem
        schema: v13
        index:
          prefix: loki_index_
          period: 24h
  storage:
    type: filesystem

singleBinary:
  replicas: 1
  persistence:
    enabled: true
    storageClass: nfs-provisioner
    size: 50Gi

read:
  replicas: 0
write:
  replicas: 0
backend:
  replicas: 0

resultsCache:
  enabled: true

chunksCache:
  enabled: false

# Try these keys for disabling canary
lokiCanary:
  enabled: false

monitoring:
  selfMonitoring:
    enabled: false
    grafanaAgent:
      installOperator: false
    lokiCanary:
      enabled: false

test:
  enabled: false
