apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-db
  namespace: immich
spec:
  instances: 2
  imageName: ghcr.io/tensorchord/cloudnative-vectorchord:15-1.1.1

  postgresql:
    shared_preload_libraries:
      - "vchord.so"

  storage:
    size: 10Gi
    storageClass: nfs-provisioner

  superuserSecret:
    name: immich-db-superuser

  bootstrap:
    initdb:
      database: immich
      owner: immich
      secret:
        name: immich-db-user
      postInitSQL:
        - CREATE EXTENSION IF NOT EXISTS vchord CASCADE;
        - CREATE EXTENSION IF NOT EXISTS earthdistance CASCADE;
        - CREATE EXTENSION IF NOT EXISTS cube CASCADE;
