immich:
  persistence:
    library:
      existingClaim: immich-library

  machineLearning:
    enabled: false

controllers:
  main:
    containers:
      main:
        image:
          tag: v2.7.5
        env:
          DB_HOSTNAME: "immich-db-rw.immich.svc.cluster.local"
          DB_PORT: "5432"
          DB_DATABASE_NAME: "immich"
          DB_USERNAME: "immich"
          DB_PASSWORD:
            valueFrom:
              secretKeyRef:
                name: immich-db-user
                key: password

valkey:
  enabled: true

server:
  enabled: true
  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        cert-manager.io/cluster-issuer: letsencrypt-cloudflare
      hosts:
        - host: photos.labmatt.com
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - photos.labmatt.com
          secretName: labmatt-com-tls
