apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-standard-config
  namespace: downloads-standard
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-provisioner
  resources:
    requests:
      storage: 5Gi
