# Jellyfin image
image:
  repository: jellyfin/jellyfin
  tag: latest
  pullPolicy: IfNotPresent

# Persistence for config/metadata
persistence:
  config:
    enabled: true
    storageClass: nfs-provisioner
    accessMode: ReadWriteOnce
    size: 100Gi

  media:
    enabled: true
    existingClaim: jellyfin-media

# Service configuration
service:
  type: ClusterIP
  port: 8096

# Ingress for access via nginx
ingress:
  enabled: true
  className: nginx
  hosts:
    - host: jellyfin.labmatt.com
      paths:
        - path: /
          pathType: Prefix
    - host: mattflix.labmatt.com
      paths:
        - path: /
          pathType: Prefix
