apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-standard
  namespace: downloads-standard
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: media-standard-downloads
  resources:
    requests:
      storage: 18Ti
