apiVersion: v1
kind: Service
metadata:
  name: graphite-exporter
  namespace: observability
  labels:
    app: graphite-exporter
spec:
  type: NodePort
  ports:
    - name: graphite
      port: 2003
      protocol: TCP
      targetPort: 2003
      nodePort: 32003
    - name: metrics
      port: 9108
      protocol: TCP
      targetPort: 9108
      nodePort: 32108
  selector:
    app: graphite-exporter
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphite-exporter
  namespace: observability
spec:
  replicas: 1
  selector:
    matchLabels:
      app: graphite-exporter
  template:
    metadata:
      labels:
        app: graphite-exporter
    spec:
      containers:
        - name: graphite-exporter
          image: prom/graphite-exporter:v0.17.0
          ports:
            - containerPort: 2003
              name: graphite
            - containerPort: 9108
              name: metrics
          args:
            - "--graphite.listen-address=:2003"
