apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  namespace: database
spec:
  bootstrap:
    initdb:
      database: jfstat
      owner: app
  managed:
    roles:
      - name: sonarr-anime
        ensure: present
        login: true
        passwordSecret:
          name: postgres-sonarr-anime
      - name: radarr
        ensure: present
        login: true
        passwordSecret:
          name: postgres-radarr
      - name: radarr-portuguese
        ensure: present
        login: true
        passwordSecret:
          name: postgres-radarr-portuguese
      - name: sonarr
        ensure: present
        login: true
        passwordSecret:
          name: postgres-sonarr
      - name: sonarr-portuguese
        ensure: present
        login: true
        passwordSecret:
          name: postgres-sonarr-portuguese
  postgresql:
    pg_hba:
      - host sonarr-standard-main,sonarr-standard-log sonarr all scram-sha-256
      - host sonarr-standard-main,sonarr-standard-log all all reject
      - host all sonarr all reject

      - host radarr-main,radarr-log radarr all scram-sha-256
      - host radarr-main,radarr-log all all reject
      - host all radarr all reject

      - host sonarr-anime-main,sonarr-anime-log sonarr-anime all scram-sha-256
      - host sonarr-anime-main,sonarr-anime-log all all reject
      - host all sonarr-anime all reject

      - host sonarr-portuguese-main,sonarr-portuguese-log sonarr-portuguese all scram-sha-256
      - host sonarr-portuguese-main,sonarr-portuguese-log all all reject
      - host all sonarr-portuguese all reject

      - host radarr-portuguese-main,radarr-portuguese-log radarr-portuguese all scram-sha-256
      - host radarr-portuguese-main,radarr-portuguese-log all all reject
      - host all radarr-portuguese all reject
  instances: 2
  affinity:
    podAntiAffinityType: required
    topologyKey: topology.eye-of-michael/physical-host
  storage:
    size: 50Gi
    storageClass: nfs-provisioner
  inheritedMetadata:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "jellyfin,signal-messaging,downloads-standard,observability"
