apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  namespace: database
spec:
  bootstrap:
    initdb:
      database: jfstat
      owner: app
  instances: 2
  affinity:
    podAntiAffinityType: required
    topologyKey: topology.eye-of-michael/physical-host
  storage:
    size: 50Gi
    storageClass: nfs-provisioner
  inheritedMetadata:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "jellyfin,signal-messaging,downloads-standard"
