apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bazarr-config-iscsi
  namespace: downloads-standard
spec:
  accessModes:
    - ReadWriteOncePod
  storageClassName: truenas-iscsi
  resources:
    requests:
      storage: 5Gi
