apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gotk-components.yaml
  - gotk-sync.yaml
  - observability.yaml
  - database.yaml
  - storage.yaml
  - cert-manager.yaml
  - ingress.yaml
  - ci-cd.yaml
  - intel-gpu-plugin.yaml
  - tunnel.yaml
  - downloads-standard.yaml
  - immich.yaml
  - jellyfin.yaml
  - code-for-boston.yaml
