# Flux-managed. See clusters/eye-of-michael/flux-system/project-management.yaml
# for the Kustomization CR that reconciles this path.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - leantime/database.yaml
  - leantime/secret.yaml
  - leantime/pvc.yaml
  - leantime/deployment.yaml
  - leantime/service.yaml
  - leantime/ingress.yaml
