apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: autobrr-config
  namespace: downloads-standard
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: truenas-iscsi
  resources:
    requests:
      storage: 1Gi
