apiVersion: v1
kind: Secret
metadata:
  name: leantime-postgres-credentials
  namespace: code-for-boston
  annotations:
    reflector.v1.k8s.emberstack.com/reflects: "code-for-boston-database/leantime-postgres-credentials"
